// Generated by 文心一言
/*
import React, { useState } from 'react';
import { StarOutlined, StarFilled } from '@ant-design/icons';

const MyStar = ({ form }) => {
  const [rating, setRating] = useState(5);

  const handleStarClick = (newRating) => {
    setRating(newRating);
    form.setFieldsValue({ rating: newRating })
  };

  const renderStars = () => {
    return Array.from({ length: 5 }, (_, index) => {
      const isFilled = index < rating;
      const IconComponent = isFilled ? StarFilled : StarOutlined;
      return (
        <IconComponent
          key={index}
          onClick={() => handleStarClick(index + 1)}
          className={isFilled ? 'filled-star' : 'empty-star'}
        />
      );
    });
  };

  return (
    <div>
      {renderStars()}
      { <p>Rating: {rating}</p> }
    </div>
  );
};

export default MyStar;
*/

import React from 'react';
import { StarFilled, StarOutlined } from '@ant-design/icons';

const MyStar = ({ rating }) => {
  const renderStars = () => {
    const fullStars = [];
    const emptyStars = [];

    for (let i = 1; i <= 5; i++) {
      if (i <= rating) {
        fullStars.push(<StarFilled key={`full-${i}`} />);
      } else {
        emptyStars.push(<StarOutlined key={`empty-${i}`} />);
      }
    }

    return (
      <div className="star-container">
        {fullStars}
        {emptyStars}
      </div>
    );
  };

  return renderStars();
};

export default MyStar;