// Generated by 文心一言
import React, { useState } from 'react';  
import { StarOutlined, StarFilled } from '@ant-design/icons';  
  
const StarRating = () => {  
  const [rating, setRating] = useState(0);  
  
  const handleStarClick = (newRating) => {  
    setRating(newRating);  
  };  
  
  const renderStars = () => {  
    return Array.from({ length: 5 }, (_, index) => {  
      const isFilled = index < rating;  
      const IconComponent = isFilled ? StarFilled : StarOutlined;  
      return (  
        <IconComponent  
          key={index}  
          onClick={() => handleStarClick(index + 1)}  
          className={isFilled ? 'filled-star' : 'empty-star'}  
        />  
      );  
    });  
  };  
  
  return (  
    <div>  
      {renderStars()}  
      <p>Rating: {rating}</p>  
    </div>  
  );  
};  
  
export default StarRating;