// generated by 文心一言
import { effect, reducer } from 'dva';

export default {
  namespace: 'counter',
  state: {
    value: 0, // 初始值  
  },
  effects: {
    *increment({ payload }, { call, put, select }) {
      const { value } = yield select(state => state.counter); // 正确获取状态  
      yield put({
        type: 'update',
        payload: { value: value + payload }, // 增加值  
      });
    },
    *decrement({ payload }, { call, put, select }) {
      const { value } = yield select(state => state.counter); // 正确获取状态  
      yield put({
        type: 'update',
        payload: { value: value - payload }, // 减少值  
      });
    },
    /*
    *update({ payload }, { call, put, select }) {
      const { value } = yield select(state => state.counter);
      yield put({
        type: 'update',
        payload: { value: payload },
      });
    },
    */
  },
  reducers: {
    update(state, { payload }) {
      return { ...state, ...payload }; // 更新状态  
    },
  },
};